{% set name = "brian2genn" %}
{% set version = "1.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Brian2GeNN-{{ version }}.tar.gz
  sha256: 7d02968c17b72d69e5a98e9114551b69da24cc71e169e16f2a5a95a0374698d7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - brian2 >=2.4.2
    - python >=3.6
    - six

test:
  imports:
    - brian2genn
    - brian2genn.sphinxext
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/brian-team/brian2genn
  summary: An interface to use the GeNN framework as a device in Brian 2
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
